2023-06-05 18:31:25,212  ERROR       send_post.py  run  HTTPConnectionPool(host='0.0.0.0', port=9624): Max retries exceeded with url: /test (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcc491dfaf0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2023-06-05 18:31:36,456  ERROR       send_post.py  main  scene is not correct
2023-06-06 10:53:54,332  ERROR       send_post.py  run_rtsp_gpu  frame_192.168.0.20 is not update
2023-06-06 10:53:59,338  ERROR       send_post.py  run_rtsp_gpu  frame_192.168.0.20 is not update
2023-06-06 10:54:04,344  ERROR       send_post.py  run_rtsp_gpu  frame_192.168.0.20 is not update
2023-06-06 10:54:09,351  ERROR       send_post.py  run_rtsp_gpu  frame_192.168.0.20 is not update
2023-06-06 10:54:14,354  ERROR       send_post.py  run_rtsp_gpu  frame_192.168.0.20 is not update
